# Generated by Django 6.0.3 on 2026-04-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0003_subsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubcategory',
            name='category',
        ),
    ]
