# Generated by Django 6.0.3 on 2026-04-11 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0004_remove_subsubcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sampleapp.subsubcategory'),
        ),
    ]
