# Generated by Django 6.0.2 on 2026-04-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0007_alter_signup_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordreset',
            name='token',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
